name: lms
description: "Learning Management System"

publish_to: 'Egyptian Air Force'


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  intl:
  cupertino_icons: ^1.0.8
  video_player: ^2.10.1
  google_fonts: ^6.3.2
  table_calendar: ^3.2.0
  image_picker:
  flutter_svg: ^2.2.1
  dio: ^5.9.0
  equatable:
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  awesome_dialog: ^3.3.0
  flutter_secure_storage: ^9.2.4
  file_picker: ^10.3.3
  fl_chart: ^1.1.1
  provider: ^6.1.5+1
  image_picker_web:
  cached_network_image:
  animations:
  permission_handler:
  flutter_dropzone:
  web: ^1.1.1
  dart_code_metrics:
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/test_images/
    - assets/images/wing.svg
    - assets/icons/delete_icon.svg
    - assets/icons/list_announcement_icon.svg





  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf



